//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wam.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class WamAppEntities1 : DbContext
    {
        public WamAppEntities1()
            : base("name=WamAppEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Application> Applications { get; set; }
        public virtual DbSet<Developer> Developers { get; set; }
        public virtual DbSet<Page> Pages { get; set; }
        public virtual DbSet<Widget> Widgets { get; set; }
        public virtual DbSet<FormElement> FormElements { get; set; }
        public virtual DbSet<FormElementChoice> FormElementChoices { get; set; }
        public virtual DbSet<Following> Followings { get; set; }
    }
}
