//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wam.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Widget
    {
        public Widget()
        {
            this.FormElements = new HashSet<FormElement>();
        }
    
        public int Id { get; set; }
        public string name { get; set; }
        public Nullable<int> pageId { get; set; }
        public string widgetType { get; set; }
        public string url { get; set; }
        public string href { get; set; }
        public string src { get; set; }
        public string html { get; set; }
        public string style { get; set; }
        public string cssClass { get; set; }
        public Nullable<int> width { get; set; }
        public Nullable<int> height { get; set; }
        public string value { get; set; }
        public Nullable<int> order { get; set; }
    
        public virtual Page Page { get; set; }
        public virtual ICollection<FormElement> FormElements { get; set; }
    }
}
