//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

public partial class Fish
{
    public Fish()
    {
        this.Pictures = new HashSet<Picture>();
    }

    public int Id { get; set; }
    public Nullable<int> tripId { get; set; }
    public string name { get; set; }
    public Nullable<double> weight { get; set; }
    public Nullable<double> length { get; set; }
    public Nullable<System.DateTime> caughtDate { get; set; }
    public string species { get; set; }

    public virtual Trip Trip { get; set; }
    public virtual ICollection<Picture> Pictures { get; set; }
}

public partial class Picture
{
    public int Id { get; set; }
    public string file { get; set; }
    public Nullable<int> fishId { get; set; }

    public virtual Fish Fish { get; set; }
}

public partial class SecurityToken
{
    public int Id { get; set; }
    public Nullable<System.Guid> token { get; set; }
}

public partial class Trip
{
    public Trip()
    {
        this.Fish = new HashSet<Fish>();
    }

    public int Id { get; set; }
    public Nullable<System.DateTime> startDate { get; set; }
    public Nullable<System.DateTime> endDate { get; set; }
    public Nullable<int> userId { get; set; }
    public string name { get; set; }

    public virtual ICollection<Fish> Fish { get; set; }
    public virtual USER USER { get; set; }
}

public partial class USER
{
    public USER()
    {
        this.Trips = new HashSet<Trip>();
    }

    public int Id { get; set; }
    public string username { get; set; }
    public string password { get; set; }

    public virtual ICollection<Trip> Trips { get; set; }
}
