//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WamApplication
{
    using System;
    using System.Collections.Generic;
    
    public partial class Developer
    {
        public Developer()
        {
            this.Application = new HashSet<Application>();
        }
    
        public int Id { get; set; }
        public string firstName { get; set; }
        public string lastName { get; set; }
        public string username { get; set; }
        public string password { get; set; }
    
        public virtual ICollection<Application> Application { get; set; }
    }
}
