//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WamApplication
{
    using System;
    using System.Collections.Generic;
    
    public partial class Region
    {
        public int Id { get; set; }
        public string name { get; set; }
        public string content { get; set; }
        public Nullable<int> pageId { get; set; }
        public Nullable<int> width { get; set; }
        public Nullable<int> height { get; set; }
        public Nullable<int> top { get; set; }
        public Nullable<int> left { get; set; }
        public string bgColor { get; set; }
        public string fgColor { get; set; }
    
        public virtual Page Page { get; set; }
    }
}
