//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fish360Project
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class f360Entities : DbContext
    {
        public f360Entities()
            : base("name=f360Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Fish> Fish { get; set; }
        public virtual DbSet<Species> Species { get; set; }
        public virtual DbSet<Trips> Trips { get; set; }
        public virtual DbSet<Users> Users { get; set; }
    }
}
