//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fish360Project
{
    using System;
    using System.Collections.Generic;
    
    public partial class Species
    {
        public Species()
        {
            this.Fish = new HashSet<Fish>();
        }
    
        public string type { get; set; }
    
        public virtual ICollection<Fish> Fish { get; set; }
    }
}
